accounts/urls.py
from django.urls import path
from . import views
from .views import *
app_name = 'accounts'


app_name = 'accounts'
urlpatterns = [
    path('doctors/', views.doctor_list, name='doctor_list'),
    path('login/', views.user_login, name='login'),
    path('myprofile/', views.my_profile, name='myprofile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('signup/', views.signup, name='signup'),
    path('<slug:slug>/', views.doctors_detail, name='doctors_detail'),
#################################################################################
    path('api/doctors/', DoctorListView.as_view(), name='doctor_list_api'),
    path('api/doctors/<slug:slug>/', DoctorDetailView.as_view(), name='doctors_detail_api'),
    path('api/login/', user_login_api, name='login_api'),
    path('api/myprofile/', my_profile_api, name='myprofile_api'),
    path('api/update_profile/', update_profile_api, name='update_profile_api'),
    path('api/signup/', SignupView.as_view(), name='signup_api'),
]

pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts'))
] 
if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">



    <title>Vezeta</title>

    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'static_file/img/favicon.png' %}">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'static_file/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'static_file/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'static_file/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'static_file/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'static_file/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'static_file/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'static_file/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'static_file/css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'static_file/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'static_file/css/slicknav.css' %}">

    <link rel="stylesheet" href="{% static 'static_file/css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>

<!-- header-start -->
<header>
<div class="header-area ">
    <div id="sticky-header" class="main-header-area">
        <div class="container-fluid " style="background-color: rgba(0, 29, 56, 0.8);" >
            <div class="header_bottom_border">
                <div class="row align-items-center">
                    <div class="col-xl-3 col-lg-2">
                        <div class="logo">
                            <a href="index.html">
                                <img src="{% static 'static_file/img/logo2.png' %}" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-7">
                        <div class="main-menu  d-none d-lg-block">
                            <nav>
                                <ul id="navigation">
                                    <li><a href="{% url 'accounts:doctor_list' %}">احجز دكتورك</a></li>|
                                    <li><a href="">المقالات</a></li>|
                                    <li><a href="{% url 'accounts:myprofile' %}">الصفحه الشخصيه </a></li>|
                                    <li><a href="contact.html">اتصل بنا</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                        <div class="Appointment">
                            
                            {% if user.is_authenticated %}
                            <div class="phone_num d-none d-xl-block"></div>
                            <div class="d-none d-lg-block">
                                <a class="boxed-btn3" href="">قدم نفسك</a>
                            </div>
                            {% else %}
                            <div class="phone_num d-none d-xl-block">
                                <a class="boxed-btn3" href="">سجل الدخول</a>
                            </div>
                            <div class="d-none d-lg-block">
                                <a class="boxed-btn3" style="background-color: crimson;" href="">التسجيل</a>
                            </div>
                            {% endif %}
                            
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</header>
<!-- header-end -->

{% block body %}


{% endblock body %}






<!-- footer start -->
<footer class="footer">
    <div class="footer_top">
    <div class="container">
        <div class="row">
            <div class="col-xl-3 col-md-6 col-lg-3">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                    <div class="footer_logo">
                        <a href="#">
                            <img src="{% static 'static_file/img/logo2.png' %}" alt="">
                        </a>
                    </div>
                    <p>
                        diaasalam064@gmail.com <br>
                        +201118791859 <br>
                        Shubra Elkheima, Egypt
                    </p>
                    <div class="socail_links">
                        <ul>
                            <li>
                                <a href="https://www.facebook.com/m7modsabra">
                                    <i class="ti-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.youtube.com/channel/UC7FFcZc90vE5FfR_dgA_dVg?view_as=subscriber">
                                    <i class="fa fa-youtube"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/Mahmod_Raouf">
                                    <i class="fa fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/Mahmod_Raouf">
                                    <i class="fa fa-instagram"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-xl-2 col-md-6 col-lg-2">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                    <h3 class="footer_title">
                        ماذا عنا
                    </h3>
                    <ul>
                        <li><a href="https://code4learn.teachable.com/p/online-courses">من نحن </a></li>
                        <li><a href="https://code4learn.teachable.com/p/online-courses"> أسعارنا</a></li>
                        <li><a href="https://www.facebook.com/m7modsabra">إستفسار</a></li>
                    </ul>
    
                </div>
            </div>
            <div class="col-xl-3 col-md-6 col-lg-3">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                    <h3 class="footer_title">
                        الخدمات
                    </h3>
                    <ul>
                        <li><a href="https://code4learn.teachable.com/p/soundcloud">اعمالنا</a></li>
                        <li><a href="https://twitter.com/code4learn/status/1236082742582001670?s=21">شركائنا</a></li>
                        <li><a href="https://code4learn.teachable.com/p/online-courses">الخصومات والمشاريع</a></li>
                        <li><a href="https://www.facebook.com/m7modsabra">للإعلان</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xl-4 col-md-6 col-lg-4">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                    <h3 class="footer_title">
                        Subscribe
                    </h3>
                    <form action="#" class="newsletter_form">
                        <input type="text" placeholder="Enter your mail">
                        <button type="submit">Subscribe</button>
                    </form>
                    <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                        luckily.</p>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
    <div class="container">
        <div class="footer_border"></div>
        <div class="row">
            <div class="col-xl-12">
                <p class="copy_right text-center">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
    </div>
    </footer>
    <!--/ footer end  -->
    
    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'static_file/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'static_file/js/popper.min.js' %}"></script>
    <script src="{% static 'static_file/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static 'static_file/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'static_file/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'static_file/js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'static_file/js/ajax-form.js' %}"></script>
    <script src="{% static 'static_file/js/waypoints.min.js' %}"></script>
    <script src="{% static 'static_file/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'static_file/js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'static_file/js/scrollIt.js' %}"></script>
    <script src="{% static 'static_file/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'static_file/js/wow.min.js' %}"></script>
    <script src="{% static 'static_file/js/nice-select.min.js' %}"></script>
    <script src="{% static 'static_file/js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'static_file/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'static_file/js/plugins.js' %}"></script>
    <script src="{% static 'static_file/js/gijgo.min.js' %}"></script>
    
    
    
    <!--contact js-->
    <script src="{% static 'static_file/js/contact.js' %}"></script>
    <script src="{% static 'static_file/js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'static_file/js/jquery.form.js' %}"></script>
    <script src="{% static 'static_file/js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'static_file/js/mail-script.js' %}"></script>
    
    
    <script src="{% static 'static_file/js/main.js' %}"></script>
    </body>
    
    </html>