accounts/urls.py
from django.urls import path
from . import views
from .views import *
app_name = 'accounts'


app_name = 'accounts'
urlpatterns = [
    path('doctors/', views.doctor_list, name='doctor_list'),
    path('login/', views.user_login, name='login'),
    path('myprofile/', views.my_profile, name='myprofile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('signup/', views.signup, name='signup'),
    path('<slug:slug>/', views.doctors_detail, name='doctors_detail'),
#################################################################################
    path('api/doctors/', DoctorListView.as_view(), name='doctor_list_api'),
    path('api/doctors/<slug:slug>/', DoctorDetailView.as_view(), name='doctors_detail_api'),
    path('api/login/', user_login_api, name='login_api'),
    path('api/myprofile/', my_profile_api, name='myprofile_api'),
    path('api/update_profile/', update_profile_api, name='update_profile_api'),
    path('api/signup/', SignupView.as_view(), name='signup_api'),
]

pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts'))
] 
if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from distutils.command.upload import upload
from email.headerregistry import Address
# from datetime import datetime
from django.db import models
from django.db.models import OneToOneField
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.utils.text import slugify

# Create your models here.

TYPE_OF_PERSON=(
    ('M' , "Male"),
    ('F' , "Female"),
)

class Profile(models.Model):
    user = OneToOneField(User, verbose_name=_("user"), on_delete=models.CASCADE)
    name = models.CharField(_("الأسم:"), max_length=30, blank=True, null=True)
    subtitle = models.CharField(_("نبذة عنك:"), max_length=100, blank=True, null=True)
    address = models.CharField(_("المحافظه:"), max_length=50, blank=True, null=True)
    numberphone = models.CharField(_("رقم الهاتف:"), max_length=14, blank=True, null=True)
    workhour = models.CharField(_("عدد ساعات العمل :"), max_length=4, blank=True, null=True)
    waittime = models.IntegerField(_("مدة الانتظار"), blank=True, null=True)
    who_i = models.TextField(_("من انا:"), max_length=250, blank=True, null=True)
    price = models.IntegerField(_("السعر:"), blank=True, null=True)
    image = models.ImageField(_("الصورة الشخصية"), upload_to='Profile', blank=True, null=True)
    spicialist = models.CharField(_("متخصص في :"), max_length=50, blank=True, null=True)
    type_of_person = models.CharField(_("النوع"), choices= TYPE_OF_PERSON, max_length=50, blank=True, null=True)
    twiter = models.CharField(_("تويتر"), max_length=100, blank=True, null=True)
    facebook = models.CharField(_("فيسبوك"), max_length=100, blank=True, null=True)
    gmail = models.CharField(_("جميل"), max_length=100, blank=True, null=True)
    slug = models.SlugField(_("slug"), blank=True, null=True)


    def save (self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user.username)
        super(Profile, self).save(*args, **kwargs)




    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")


    def __str__(self):
        return '%s' %(self.user.username)


def create_profile(sender, **kwargs):
    if kwargs['created']:
        Profile.objects.create(user = kwargs['instance'])

post_save.connect(create_profile, sender = User)

accounts/forms.py
from cProfile import label
from dataclasses import field
from socket import fromshare
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserCreationForms(UserCreationForm):
    username = forms.CharField(label='الاسم')
    first_name = forms.CharField(label='الاسم الاول')
    last_name = forms.CharField(label='الاسم الاخير')
    email = forms.EmailField(label='ايميل')
    password1 = forms.CharField(label='كلمة السر', widget=forms.PasswordInput(), min_length=8)
    password2 = forms.CharField(label='اعادة كلمة السر', widget=forms.PasswordInput(), min_length=8)
    class Meta:
        model = User
        fields = ('username', 'first_name','last_name','email','password1','password2')


class Login_Form(forms.ModelForm):
    username = forms.CharField(label='الاسم')
    password = forms.CharField(label='باسورد', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')

class UpdateUserForm(forms.ModelForm):
    first_name = forms.CharField(label='الاسم الاول')
    last_name = forms.CharField(label='الاسم الاخير')
    email = forms.EmailField(label='ايميل')
    class Meta:
        model = User
        fields = ('first_name', 'last_name','email')


class UpdateProfileForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ('name', 'subtitle','address','numberphone','workhour','waittime','who_i','price','image','spicialist','type_of_person','twiter','facebook','gmail')
    

accounts/views.py
from ast import Not
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .models import Profile
from .forms import Login_Form , UpdateUserForm , UserCreationForms , UpdateProfileForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

# Create your views here.


def doctor_list(request):
    doctors = User.objects.all()
    return render(request, 'users/doctor_list.html', {
        'doctors' : doctors,})

def doctors_detail(request, slug):
    doctors_detail = Profile.objects.get(slug = slug)
    return render(request, 'users/doctors_detail.html', {'doctors_detail': doctors_detail})

def user_login(request):
    if request.method == 'POST':
        form = Login_Form()
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username , password=password)
        if user is not None:
            login(request , user)
            return redirect('accounts:doctor_list')
    else:
        form = Login_Form()

    return render(request, 'users/login.html', {'form': form})

@login_required()
def my_profile(request):
    return render(request, 'users/myprofile.html', {})


def update_profile(request):
    user_form = UpdateUserForm(instance=request.user)
    profile_form = UpdateProfileForm(instance=request.user.profile) 
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, instance=request.user.profile) 
        if user_form.is_valid and profile_form.is_valid:
            user_form.save()
            profile_form.save()
            return redirect('accounts:doctor_list')

    return render(request, 'users/update_profile.html', {'user_form':user_form, 'profile_form':profile_form})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForms(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username , password=password)
            login(request , user)
            return redirect('accounts:doctor_list')
    else:
        form = UserCreationForms()
    return render(request, 'users/signup.html', {'form':form})
#########################################################################################
    
from rest_framework import generics, permissions
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework import status
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .models import Profile
from .serializers import UserSerializer, ProfileSerializer, UserCreationSerializer
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

# Import your serializers, UpdateUserForm, and UpdateProfileForm here

@api_view(['POST'])
def user_login_api(request):
    if request.method == 'POST':
        username = request.data.get('username')
        password = request.data.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return Response({'detail': 'Login successful'}, status=status.HTTP_200_OK)
        else:
            return Response({'detail': 'Invalid credentials'}, status=status.HTTP_401_UNAUTHORIZED)

@api_view(['GET'])
@permission_classes([permissions.IsAuthenticated])
def my_profile_api(request):
    serializer = UserSerializer(request.user)
    return Response(serializer.data)

@api_view(['PUT'])
@permission_classes([permissions.IsAuthenticated])
def update_profile_api(request):
    user = request.user
    user_serializer = UserSerializer(user, data=request.data, partial=True)
    profile_serializer = ProfileSerializer(user.profile, data=request.data.get('profile'), partial=True)

    if user_serializer.is_valid() and profile_serializer.is_valid():
        user_serializer.save()
        profile_serializer.save()
        return Response({'detail': 'Profile updated successfully'}, status=status.HTTP_200_OK)
    else:
        return Response({'detail': 'Invalid data'}, status=status.HTTP_400_BAD_REQUEST)

class DoctorListView(generics.ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class DoctorDetailView(generics.RetrieveAPIView):
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer
    lookup_field = 'slug'

@method_decorator(csrf_exempt, name='dispatch')
class SignupView(generics.CreateAPIView):
    serializer_class = UserCreationSerializer
    permission_classes = [permissions.AllowAny]

    def perform_create(self, serializer):
        user = serializer.save()
        login(self.request, user)

accounts/templates/users/doctor_list.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
<div dir="rtl">
    {% include 'users/search.html' %}
    <!-- job_listing_area_start  -->
    <div class="job_listing_area">
        <div class="container">

            <div class="job_lists">
                <div class="row">
                    {% for doctor in doctors %}

                    <div class="col-lg-10 col-md-10" style="height: 16rem;" >
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div >
                                        {% if doctor.profile.image %}
                                            <img  src="{{doctor.profile.image.url}}" alt="" width="100" height="100">
                                        {% else %} 
                                            <img  src="{% static 'static_file/img/candiateds/1.png' %}" alt="" width="100" height="100">
                                        {% endif %}
                                        
                                </div>
                                <div class="jobs_conetent">
                                    <a href="{% url 'accounts:doctors_detail' doctor.profile.slug %}"><h5>دكتور </h5></a>
                                    <h6>{{doctor.profile.name}}</h6>
                                    
                                    <div class="links_locat">
                                        <div class="location">
                                            <p> <i class="fas fa-briefcase-medical"></i> دكتور <span style="color: blue;">{{doctor.profile.name}}</span> متخصص في <span style="color: blue;">{{doctor.profile.spicialist}}</span></p>
                                            <p> <i class="fa fa-map-marker"></i>{{doctor.profile.address}}</p>
                                            <p> <i class="fa fa-map-marker"></i> الكشف : <span style="color: blue;">{{doctor.profile.price}}</span>جنية</p>
                                            <p> <i class="fa fa-clock-o"></i> مدة الانتظار : <span style="color: blue;">{{doctor.profile.waittime}}</span> ساعه</p>
                                            <p> <i class="fa fa-clock-o"></i> عدد ساعات العمل : <span style="color: blue;">{{doctor.profile.workhour}}</span> ساعه</p>
                                            <p> <i class="fa fa-clock-o"></i>سعر المكالمه العادية  :<span style="color: blue;"> {{doctor.profile.numberphone}}</span>  </p>


                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="boxed-btn3" href="">حجز كشف</a>
                                </div>

                                <div class="rating">
                                    <div class="text-warning">
                                        <!-- to make image category for clinic image -->
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        </div>
                                    <div class="rating" >
                                        <h5>تقييم الدكتور</h5>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    {% endfor %}


                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
</div>
    <!-- featured_candidates_area_start  -->
    <div class="featured_candidates_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section_title text-center mb-40">
                        <h3>المرشحين المميزين</h3>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="candidate_active owl-carousel">
                        <div class="single_candidates text-center">
                            <div class="thumb">
                                <img class="img-circle " src="img/candiateds/2.png" alt="" >
                                
                            </div>
                            <a href="" ><h4 >الاسم</h4></a>
                            <p>  التخصص</p>
                            <div class="best-rating">
                                <div class="text-warning">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        
                                </div>
                                <div class="best-rating" >
                                    <h5>تقييم الدكتور</h5>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- featured_candidates_area_end  -->
    {% endblock body %}
    

accounts/templates/users/doctors_detail.html
{% extends 'base.html' %}
{% load static %}


{% block body %}


<div dir="rtl">

    {% include 'users/search.html' %}

<div class="job_details_area">
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="job_details_header">
                <div class="single_jobs white-bg d-flex justify-content-between">
                    <div class="jobs_left d-flex align-items-center">
                        <div >
                                {% if doctors_detail.image %}
                                    <img class="img-circle" src="{{doctors_detail.image.url}}" alt="" width="100" height="100">
                                {% else %}
                                    <img class="img-circle" src="{% static 'static_file/img/candiateds/1.png'%}" alt="" width="100" height="100"> 
                                {% endif %}

                            
                        </div>
                        <div class="jobs_conetent">
                            <a href="#" ><h4>{{doctors_detail.name}}</h4></a>
                            <div class="links_locat d-flex align-items-center">
                                <div class="location">
                                    <p> <i class="fa fa-map-marker"></i> مصر  , {{doctors_detail.address}}</p>
                                </div>
                                <div class="location">
                                    <p> <i class="fa fa-clock-o"></i>  وقت الانتظار  دقيقه {{doctors_detail.waittime}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="jobs_right">
                        <div class="apply_now">
                            <a class="boxed-btn3" href="">حجز كشف</a>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="descript_wrap white-bg">
                <div class="single_wrapp">
                    <h3>نبذه عن الدكتور </h3>
                    <p>{{doctors_detail.subtitle}}</p>
                </div>
                <div class="white-card white-card-inner">
                    <div class="single_wrap" style="margin-top: 10px;">
                        <h4>معلومات عن الدكتور</h4>
                        <ul>
                            <p>{{doctors_detail.who_i}}</p>
                        </ul>
                    </div>
                </div>
                <div class="single_wrap">
                    <h4>خدمات الدكتور :</h4>
                    <ul>
                        <p class="tagitem disable-click pull-left mr-4" style="background-color: #f5f5f5;
                        color: #808184;"> {{doctors_detail.spicialist}} 
                        </p>
                        <p class="tagitem disable-click pull-left" style="background-color: #f5f5f5;
                        color: #808184;">استشاري جراحه وتجميل الاسنان 
                        </p>
                    </ul>
                    <br>
                </div>
                <div class="single_wrap">
                    <h4>صور العيادة :</h4>
                            <img class="image_clinic" src="img/candiateds/2.png" alt="" >
                            <img class="image_clinic" src="img/candiateds/2.png" alt="" >
                            <img class="image_clinic" src="img/candiateds/2.png" alt="" >
                    


                </div>
            </div>

    <!-- comments -->
    <div class="section-row">
        <div class="section-title">
            <h2 style="color: brown;">التعليقات (  )</h2>
        </div>

        <div class="post-comments" >

            <!-- comment -->
            <div class="media">
                <div class="media-left">
                    <img class="media-object" src="img/avatar.png" alt="">
                </div>
                <div class="media-body " >
                    <div class="media-heading">
                        <h4>اسم الكاتب</h4>
                        <span class="time">تم التعليق في </span>
                    </div>
                    <p>الكومنتات</p>
                    <a href="#" class="reply">الردود ..</a>

                    <!-- comment -->
                    <div class="media">
                        <div class="media-left">
                            <img class="media-object" src="" alt="">
                        </div>
                        <div class="media-body">
                            <div class="media-heading">
                                <h4>محمود عبد الرؤف صبره</h4>
                                <span class="time">تم التعليق فى </span>
                            </div>
                            <p>شكرا جدا واتمنى ان تتصفح باقي المواضيع .....</p>
                        </div>
                    </div>
                    <!-- /comment -->
                </div>
            </div>
            <!-- /comment -->

            <div class="media-heading">
                <h4>لا يوجد تعليقات حتى الأن ..</h4>
            </div>

        </div>
    </div>
    <!-- /comments -->                    
    <div class="apply_job_form white-bg">
        <h4>إترك تعليقك</h4>
        <form method="POST" >

            <div class="row">
                <div class="col-md-6">
                    <div class="input_field">
                        <input type="text"  placeholder=" الإسم">
                        
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input_field">
                        <input type="text"  placeholder=" الإيميل">
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="input_field">
                        <textarea  cols="30" rows="10" placeholder="تعليقك .."></textarea>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="submit_btn">
                        <button class="boxed-btn3 w-100" type="submit">تعليق</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
        </div>
        <div class="col-lg-4">
            <div class="job_sumary">
                <div class="summery_header">
                    <h3>معلومات عن الدكتور </h3>
                </div>
                <div class="job_content">
                    <ul>
                        <li>  انضم إلينا : <span style="color: blue;"></span></li>
                        <li> الكشف : <span style="color: blue;"> {{ doctors_detail.price }}جنية</span></li>
                        <li> رقم الهاتف : <span style="color: blue;">{{ doctors_detail.numberphone }}</span></li>
                        <li>عدد ساعات العمل : <span style="color: blue;">{{ doctors_detail.workhour }} ساعات</span></li>
                    </ul>
                    
                </div>
            </div>
            <div class="share_wrap d-flex">
                <span>شارك الصفحه :</span>
                <ul>
                    <li><a href=""> <i class="fa fa-facebook"></i></a> </li>
                    <li><a href=""> <i class="fa fa-google-plus"></i></a> </li>
                    <li><a href=""> <i class="fa fa-twitter"></i></a> </li>
                    <li><a href=""> <i class="fa fa-envelope"></i></a> </li>
                </ul>
            </div>
            <div class="job_location_wrap">
                <div class="job_lok_inner">
                    <div id="map" style="height: 200px;"></div>
                    <script>
                        function initMap() {
                        var uluru = {lat: -25.363, lng: 131.044};
                        var grayStyles = [
                            {
                            featureType: "all",
                            stylers: [
                                { saturation: -90 },
                                { lightness: 50 }
                            ]
                            },
                            {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                        ];
                        var map = new google.maps.Map(document.getElementById('map'), {
                            center: {lat: -31.197, lng: 150.744},
                            zoom: 9,
                            styles: grayStyles,
                            scrollwheel:  false
                        });
                        }
                        
                    </script>
                    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                    
                    </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>


{% endblock body %}
    

accounts/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}
<div dir="rtl">
    <div class="container">
        <div class="signup">
            <div class="col-md-9">
                <form method="POST" enctype="multipart/form-data">
                    <h4 class="auth-header">تسجيل الدخول</h4>
                    {% csrf_token %}
                    <div class="form-group">
                        {{form.username|as_crispy_field}}
                    </div>
                    <div class="form-group">
                        {{ form.password|as_crispy_field }}
                    </div>
                    <div class="buttons-w">
                        <button type="submit" class="btn btn-success ml-5">تسجيل</button>
                    </div>
                    <select name="ccc" id="">
                        <option value="heart">heart sp</option>
                        <option value="eay">eay sp</option>
                    </select>
                    <div>{{ specializing }}</div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

accounts/templates/users/search.html
<!-- Search -->
<div class="catagory_area ">
    <div class="container " style="margin-top: 10rem">
                <div class=" single_text">
                    <h2>احجز مع
                        أفضل دكتور في مصر</h3>
                    <h3>احجز اونلاين او كلم  ١٧٧٥۸</h4>
                    <h4>١٦٠٠٠ دكتور -٤٠٠٠ استاذ واستشاري - اكثر من ۲٠ تخصص</h5>
                    <br>
                </div>
                <form  method="GET" action="">
                <div class="row cat_search" >
    
                    <div class="col-lg-3 col-md-4">
                        <div class="single_input">
                            <input type="text" placeholder="إسم الدكتور" >
                        </div>
                    </div>
    
                    <div class="col-lg-3 col-md-4">
                        <div class="single_input">
                            <select class="wide" >
                                <option value="" >الموقع</option>
                                <option value="المنصوره">المنصوره</option>
                                <option value="الدقي">الدقي</option>
                                <option value="4">Sylet</option>
                            </select>
                        </div>
                    </div>
    
                    <div class="col-lg-3 col-md-4">
                        <div class="single_input">
                            <select class="wide" >
                                <option value="">التخصص</option>
                                <option value="جلدية">جلدية</option>
                                <option value="اسنان">اسنان</option>
                                <option value="نفسي">نفسي</option>
                                <option value="اطفال">اطفال حديثي الولادة</option>
                                <option value="مخ">مخ واعصاب</option>
                                <option value="عظام">عظام</option>
                                <option value="نساء">نساء وتوليد</option>
                                <option value="انف">انف واذن وحنجرة</option>
                                <option value="قلب">قلب واوعية دموية</option>
                                <option value="امراض">امراض دم</option>
                                <option value="اورام">اورام</option>
                                <option value="باطنه">باطنه</option>
                                <option value="تخسيس">تخسيس وتغذية</option>
                                <option value="جاطفال">جراحة اطفال</option>
                                <option value="جاورام">جراحة اورام</option>
                                <option value="جاوعيه">جراحة اوعية دموية</option>
                                <option value="جتجميل">جراحة تجميل</option>
                                <option value="سمنه">جراحه سمنة ومناظير </option>
                                </select>
                        </div>
                    </div>
    
                    <div class="col-lg-3 col-md-12">
                        <div class="job_btn">
                            <input type="submit" class="boxed-btn3" value="ابحث هنا">
                        </div>
                    </div>
    
                </div>
                </form> 
            </div>
        </div>
        <!-- endsearch -->

accounts/templates/users/signup.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}

<div dir="rtl">
    <div class="container">
        <div class="signup">
    
        <div class="col-md-9" >
            <form method="POST" enctype="multipart/form-data">
                <h4 class="auth-header">أنشاء حساب جديد</h4>
                {% csrf_token %}
                <div class="form-group">
                    {{form.username|as_crispy_field}}
                </div>
                <div class="form-group">
                    {{form.email|as_crispy_field}}
    
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            {{form.first_name|as_crispy_field}}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            {{form.last_name|as_crispy_field}}
                    </div>
                </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            {{form.password1|as_crispy_field}}
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            {{form.password2|as_crispy_field}}
                    </div>
                </div>
                <div class="buttons-w"><button type="submit" class="btn btn-success">التسجيل</button></div>
    
            </form>
        </div>
        </div>
    </div>
    </div>
    {% endblock body %}